# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(850, 851)
        Dialog.setMinimumSize(QtCore.QSize(850, 851))
        Dialog.setMaximumSize(QtCore.QSize(850, 851))
        self.files = QtWidgets.QTableWidget(Dialog)
        self.files.setGeometry(QtCore.QRect(30, 150, 791, 351))
        self.files.setObjectName("files")
        self.files.setColumnCount(0)
        self.files.setRowCount(0)
        self.downloading_files = QtWidgets.QTableWidget(Dialog)
        self.downloading_files.setGeometry(QtCore.QRect(30, 540, 791, 51))
        self.downloading_files.setObjectName("downloading_files")
        self.downloading_files.setColumnCount(0)
        self.downloading_files.setRowCount(0)
        self.uploading_files = QtWidgets.QTableWidget(Dialog)
        self.uploading_files.setGeometry(QtCore.QRect(30, 630, 791, 51))
        self.uploading_files.setObjectName("uploading_files")
        self.uploading_files.setColumnCount(0)
        self.uploading_files.setRowCount(0)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 510, 301, 21))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 600, 221, 21))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.home_button = QtWidgets.QPushButton(Dialog)
        self.home_button.setGeometry(QtCore.QRect(30, 30, 41, 41))
        self.home_button.setText("")
        self.home_button.setObjectName("home_button")
        self.goto_button = QtWidgets.QPushButton(Dialog)
        self.goto_button.setGeometry(QtCore.QRect(780, 30, 41, 41))
        self.goto_button.setText("")
        self.goto_button.setObjectName("goto_button")
        self.back_button = QtWidgets.QPushButton(Dialog)
        self.back_button.setGeometry(QtCore.QRect(90, 30, 41, 41))
        self.back_button.setText("")
        self.back_button.setObjectName("back_button")
        self.mkdir_button = QtWidgets.QPushButton(Dialog)
        self.mkdir_button.setGeometry(QtCore.QRect(150, 90, 41, 41))
        self.mkdir_button.setText("")
        self.mkdir_button.setObjectName("mkdir_button")
        self.upload_button = QtWidgets.QPushButton(Dialog)
        self.upload_button.setGeometry(QtCore.QRect(30, 90, 41, 41))
        self.upload_button.setText("")
        self.upload_button.setObjectName("upload_button")
        self.download_button = QtWidgets.QPushButton(Dialog)
        self.download_button.setGeometry(QtCore.QRect(90, 90, 41, 41))
        self.download_button.setText("")
        self.download_button.setObjectName("download_button")
        self.disconnect_button = QtWidgets.QPushButton(Dialog)
        self.disconnect_button.setGeometry(QtCore.QRect(680, 90, 141, 41))
        self.disconnect_button.setObjectName("disconnect_button")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(150, 30, 611, 41))
        self.lineEdit.setMinimumSize(QtCore.QSize(241, 0))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 690, 201, 21))
        self.label_3.setObjectName("label_3")
        self.transferred_files = QtWidgets.QTableWidget(Dialog)
        self.transferred_files.setGeometry(QtCore.QRect(30, 720, 791, 101))
        self.transferred_files.setObjectName("transferred_files")
        self.transferred_files.setColumnCount(0)
        self.transferred_files.setRowCount(0)
        self.downloading_name = QtWidgets.QLabel(Dialog)
        self.downloading_name.setGeometry(QtCore.QRect(40, 560, 81, 31))
        self.downloading_name.setText("")
        self.downloading_name.setObjectName("downloading_name")
        self.uploading_name = QtWidgets.QLabel(Dialog)
        self.uploading_name.setGeometry(QtCore.QRect(40, 650, 81, 31))
        self.uploading_name.setText("")
        self.uploading_name.setObjectName("uploading_name")
        self.downloading_bar = QtWidgets.QProgressBar(Dialog)
        self.downloading_bar.setGeometry(QtCore.QRect(130, 560, 691, 31))
        self.downloading_bar.setProperty("value", 24)
        self.downloading_bar.setObjectName("downloading_bar")
        self.uploading_bar = QtWidgets.QProgressBar(Dialog)
        self.uploading_bar.setGeometry(QtCore.QRect(130, 650, 691, 31))
        self.uploading_bar.setProperty("value", 24)
        self.uploading_bar.setObjectName("uploading_bar")
        self.pause_button = QtWidgets.QPushButton(Dialog)
        self.pause_button.setGeometry(QtCore.QRect(630, 510, 81, 21))
        self.pause_button.setObjectName("pause_button")
        self.continue_button = QtWidgets.QPushButton(Dialog)
        self.continue_button.setGeometry(QtCore.QRect(740, 510, 81, 21))
        self.continue_button.setObjectName("continue_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Downloading file:"))
        self.label_2.setText(_translate("Dialog", "Uploading file:"))
        self.disconnect_button.setText(_translate("Dialog", "Disconnect"))
        self.label_3.setText(_translate("Dialog", "Transferrd files:"))
        self.pause_button.setText(_translate("Dialog", "Pause"))
        self.continue_button.setText(_translate("Dialog", "Continue"))
